/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.alexb.kafka.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Status { 
  ACTIVE, INACTIVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"com.alexb.kafka.model\",\"symbols\":[\"ACTIVE\",\"INACTIVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
